// <auto-generated />
using LAMovies_NET6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAMovies_NET6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230506193420_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAMovies_NET6.Models.Movie", b =>
                {
                    b.Property<int>("idMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMovie"));

                    b.Property<string>("descriptionMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("minAgeMovie")
                        .HasColumnType("int");

                    b.Property<string>("nameMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualityMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subLanguageMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timeMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriImgCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriMovieTrailer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("viewMovie")
                        .HasColumnType("int");

                    b.Property<string>("yearCreateMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMovie");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
