// <auto-generated />
using System;
using LAMovies_NET6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAMovies_NET6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230525231346_dss")]
    partial class dss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAMovies_NET6.Models.Genre", b =>
                {
                    b.Property<int>("idGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGenre"));

                    b.Property<string>("nameGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idGenre");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.Movie", b =>
                {
                    b.Property<int>("idMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMovie"));

                    b.Property<string>("descriptionMovie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("minAgeMovie")
                        .HasColumnType("int");

                    b.Property<string>("nameMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualityMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subLanguageMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timeMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriImgCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uriMovieTrailer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("viewMovie")
                        .HasColumnType("int");

                    b.Property<string>("yearCreateMovie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMovie");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.MovieGenre", b =>
                {
                    b.Property<int>("idMovie")
                        .HasColumnType("int");

                    b.Property<int>("idGenre")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("idMovie", "idGenre");

                    b.HasIndex("idGenre");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.MovieHistory", b =>
                {
                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idMovie")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeWatch")
                        .HasColumnType("datetime2");

                    b.Property<int?>("minutes")
                        .HasColumnType("int");

                    b.Property<bool?>("status")
                        .HasColumnType("bit");

                    b.HasKey("idUser", "idMovie");

                    b.HasIndex("idMovie");

                    b.ToTable("MovieHistorys");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.Pricing", b =>
                {
                    b.Property<int>("idPricing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPricing"));

                    b.Property<string>("namePricing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pricePricing")
                        .HasColumnType("float");

                    b.Property<int>("timePricing")
                        .HasColumnType("int");

                    b.HasKey("idPricing");

                    b.ToTable("Pricings");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateBirthdayUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.UserPricing", b =>
                {
                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idPricing")
                        .HasColumnType("int");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.HasKey("idUser", "idPricing");

                    b.HasIndex("idPricing");

                    b.ToTable("UserPricings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.MovieGenre", b =>
                {
                    b.HasOne("LAMovies_NET6.Models.Genre", "Genre")
                        .WithMany("MovieGenre")
                        .HasForeignKey("idGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAMovies_NET6.Models.Movie", "Movie")
                        .WithMany("MovieGenre")
                        .HasForeignKey("idMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.MovieHistory", b =>
                {
                    b.HasOne("LAMovies_NET6.Models.Movie", "Movie")
                        .WithMany("MovieHistory")
                        .HasForeignKey("idMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAMovies_NET6.Models.User", "User")
                        .WithMany("MovieHistory")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.UserPricing", b =>
                {
                    b.HasOne("LAMovies_NET6.Models.Pricing", "Pricing")
                        .WithMany("UserPricing")
                        .HasForeignKey("idPricing")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAMovies_NET6.Models.User", "User")
                        .WithMany("UserPricing")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pricing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.Genre", b =>
                {
                    b.Navigation("MovieGenre");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.Movie", b =>
                {
                    b.Navigation("MovieGenre");

                    b.Navigation("MovieHistory");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.Pricing", b =>
                {
                    b.Navigation("UserPricing");
                });

            modelBuilder.Entity("LAMovies_NET6.Models.User", b =>
                {
                    b.Navigation("MovieHistory");

                    b.Navigation("UserPricing");
                });
#pragma warning restore 612, 618
        }
    }
}
